---
- name: Install PHP and extensions
  package:
    update_cache: true
    name:
      - php
      - php8.1
      - php8.1-bcmath
      - php-common
      - php8.1-curl
      - libapache2-mod-php8.1
      - php8.1-mbstring
      - php8.1-mysql
      - php8.1-gd
      - php8.1-xml
      - php8.1-tokenizer
      - php8.1-zip
    state: latest
