---
- name: Update Repo
  package: update_cache=yes

- name: Installing snapd
  apt:
    name: snapd
    state: present

- name: Install core
  community.general.snap:
    name: core

- name: Refresh core
  command: snap refresh core

- name: Install certbot
  community.general.snap:
    name: certbot
    classic: true

- name: Configure certbot
  shell: sudo ln -s /snap/bin/certbot /usr/bin/certbot
  args:
    chdir: /usr/bin/
    creates: certbot

- name: Stop services for certificate generation
  service:
    name: "apache2"
    state: stopped

- name: Request SSL Certificate
  shell: yes | certbot --apache --agree-tos --redirect -m dewgodswill@gmail.com -d deboraholivegodswill.me

- name: Restart services after generation
  service:
    name: "apache2"
    state: started

